---
# tasks file for jenkins-install

- block: # =============== Block for Ubuntu =================

    - name: Add repository
      shell: |
      wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
      sudo install -o root -g root -m 644 packages.microsoft.gpg /etc/apt/trusted.gpg.d/
      sudo sh -c 'echo "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
    
    - name: Install apt-transport-https
      apt: name=apt-transport-https state=latest

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 
    
    - name: upgrade all packages
      apt: name=* state=latest

    - name: Install VS Code
      apt: name=code state=latest

when: ansible_os_family == "Debian"