---
# tasks file for update-upgrade

- block:    # =============== Block for RedHat =================

    - name: Update yum repo and cache
      apt: update_cache=yes force_yum_get=yes cache_valid_time=3600

    - name: upgrade all packages
      yum: name=* state=latest

  when: ansible_os_family == "RedHat"

- block:    # =============== Block for Ubuntu =================

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    
    - name: upgrade all packages
      apt: name=* state=latest

  when: ansible_os_family == "Debian"