---
# tasks file for update-upgrade

- block:    # =============== Block for RedHat =================

    - name: update all packages
      yum: name=* state=latest

  when: ansible_os_family == "RedHat"

- block:    # =============== Block for Ubuntu =================

    - name: Update apt-get repo and cache
      apt: update_cache=no force_apt_get=yes
    
    - name: upgrade all packages
      apt: name=* state=latest

  when: ansible_os_family == "Debian"