---
# tasks file for jenkins-install

- block: # =============== Block for Ubuntu =================

    - name: Uninstall jenkins
      apt: name=jenkins state=absent

    - name: Add repository
      shell: |
        wget -q -O - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
        sh -c 'echo deb https://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
        apt-get update
  
    - name: Update apt-get repo and cache
      apt: update_cache=no force_apt_get=yes 
  
    - name: upgrade all packages
      apt: name=* state=latest

    - name: Install jenkins
      apt: name=jenkins state=latest

    - name: Add jenkins user to docker group
      user:
        name: jenkins
        comment: Jenkins user
        group: docker

  when: ansible_os_family == "Debian"