---
# tasks file for idea-install

- block: # =============== Block for Ubuntu =================

    - name: Install IntelliJ Idea Community
      shell: |
        snap install intellij-idea-community --classic
  
  when: ansible_os_family == "Debian"